name: TeaSafeDrop
version: '${version}'
main: dev.nighter.teaSafeDrop.TeaSafeDrop
api-version: '1.21'
authors: [ Nighter ]
folia-supported: true
description: Protects specific items from explosions and fire
commands:
  teasafedrop:
    description: Main command for TeaSafeDrop plugin
    aliases: [ts]
    usage: /teasafedrop [reload|help]
    permission: teasafedrop.use
    permission-message: ""
permissions:
  teasafedrop.reload:
    description: Allows reloading the plugin configuration
    default: op
  teasafedrop.use:
    description: Allows using the plugin commands
    default: op