name: "🐞 Bug Report"
description: "Report a bug or issue with the plugin."
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## 🚨 Please provide as much detail as possible to help us fix the issue quickly!"

  - type: input
    id: minecraft-version
    attributes:
      label: "Minecraft Version"
      description: "Which Minecraft version are you using? (e.g., 1.21.1)"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: "Plugin Version"
      description: "Which CelestComabat version are you using? (e.g., v1.2.3)"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "📌 Bug Description"
      description: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "⚡ Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      value: |
        1. Start the server
        2. Run the command /...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📜 Logs or Errors (if applicable)"
      description: "Paste any relevant console logs or error messages here."
      render: shell