name: "✨ Feature Request"
description: "Suggest a new feature or improvement."
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## 🚀 Have an idea to improve the plugin? Let us know!"

  - type: textarea
    id: feature-description
    attributes:
      label: "🔹 Feature Description"
      description: "What feature do you want to add? How will it benefit players or server admins?"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "🔍 Additional Information"
      description: "Feel free to include examples, images, or any other relevant details."